bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12331,6 +12331,8 @@ _ACEOF
 
         fi
 
+# TODO: figure out how to find mozilla gtkembedmoz (and the library in RH 9.0 seems to be broken)
+
 	if test "$with_html" = yes ; then
 	  # Extract the first word of "mozilla-config", so it can be a program name with args.
 set dummy mozilla-config; ac_word=$2
@@ -12467,14 +12469,69 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-echo "$as_me:$LINENO: result: no" >&5
+
+	           echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
+	       	   echo "$as_me:$LINENO: checking for /usr/include/mozilla-1.2.1/gtkembedmoz/gtkmozembed.h" >&5
+echo $ECHO_N "checking for /usr/include/mozilla-1.2.1/gtkembedmoz/gtkmozembed.h... $ECHO_C" >&6
+    	           CFLAGS="$OLD_CFLAGS $GTK_CFLAGS -I/usr/include/mozilla-1.2.1"
+	           cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gtkembedmoz/gtkmozembed.h>
+int
+main ()
+{
+int g; g = (int)gtk_moz_embed_get_type()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+		       echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  	       	       cat >>confdefs.h <<\_ACEOF
+#define HAVE_HTML 1
+_ACEOF
+
+		       GTKHTML_LIB="-lgtkembedmoz"
+		       GTKHTML_FLAGS="-I/usr/include/mozilla-1.2.1"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	               echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
+rm -f conftest.$ac_objext conftest.$ac_ext # compile_ifelse
+
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext # compile_ifelse
+
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext # compile_ifelse
             CFLAGS="$OLD_CFLAGS"
 	  else
   	    cat >>confdefs.h <<\_ACEOF
