bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2915,7 +2915,7 @@ _ACEOF
 #   --with-sample-width=N use N bits of samples (default = 24)
 #   --with-esd            use Enlightened Sound Daemon
 #   --with-no-gui         make Snd without any graphics support
-#   --with-motif-prefix   set location of Motif (untested as yet)
+#   --with-motif-prefix   set location of Motif
 #   --with-static-gsl     try to statically load GSL
 #   --with-guile          try to use Guile as the extension language (default=yes)
 #   --with-ruby           try to use Ruby as the extension language
@@ -13109,7 +13109,7 @@ fi
   else
     if test x$motif_prefix != x ; then
       X_PRE_LIBS="$X_LIBS $X_PRE_LIBS -L$motif_prefix/lib -lXm -lXt"
-      XFLAGS="$XFLAGS -I$motif_prefix/include"
+      XFLAGS="-I$motif_prefix/include $XFLAGS"
     else
       X_PRE_LIBS="$X_LIBS $X_PRE_LIBS -lXm -lXt"
     fi
@@ -13840,8 +13840,10 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
- Widget w;
-                  w = XmCreateTabStack(NULL, "tab-stack", NULL, 0)
+ Widget w, w1, w2;
+                  w = XmCreateTabStack(NULL, "tab-stack", NULL, 0);
+                  /* w1 = XmTabStackXYToWidget(w, 0, 0); */
+		  w2 = XmTabStackIndexToWidget(w, 0)
 
   ;
   return 0;
@@ -13886,6 +13888,66 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+          echo "$as_me:$LINENO: checking for XmTabStackXYToWidget" >&5
+echo $ECHO_N "checking for XmTabStackXYToWidget... $ECHO_C" >&6
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Xm/XmAll.h>
+                 #include <Xm/TabStack.h>
+int
+main ()
+{
+ Widget w, w1, w2;
+                  w = XmCreateTabStack(NULL, "tab-stack", NULL, 0);
+                  w1 = XmTabStackXYToWidget(w, 0, 0)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+ 	     cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmTabStackXYToWidget 1
+_ACEOF
+
+	     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
           echo "$as_me:$LINENO: checking for XmColumn" >&5
 echo $ECHO_N "checking for XmColumn... $ECHO_C" >&6
           cat >conftest.$ac_ext <<_ACEOF
@@ -13900,9 +13962,8 @@ int
 main ()
 {
  Widget w;
-                  w = XmCreateColumn(NULL, "column", NULL, 0);
-                  w = XmColumnGetChildLabel(w)
-                  # some versions of Motif have Column.h and XmCreateColumn but not XmColumnGetChildLabel
+                  w = XmCreateColumn(NULL, "column", NULL, 0)
+                  /* w = XmColumnGetChildLabel(w) */
 
   ;
   return 0;
@@ -13933,6 +13994,66 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
 
  	     cat >>confdefs.h <<\_ACEOF
 #define HAVE_XmCreateColumn 1
+_ACEOF
+
+	     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          echo "$as_me:$LINENO: checking for XmColumnGetChildLabel" >&5
+echo $ECHO_N "checking for XmColumnGetChildLabel... $ECHO_C" >&6
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Xm/XmAll.h>
+                 #include <Xm/Column.h>
+int
+main ()
+{
+ Widget w;
+                  w = XmCreateColumn(NULL, "column", NULL, 0);
+                  w = XmColumnGetChildLabel(w)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+ 	     cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmColumnGetChildLabel 1
 _ACEOF
 
 	     echo "$as_me:$LINENO: result: yes" >&5
