bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12066,6 +12066,128 @@ _ACEOF
 
 fi
 
+   	  echo "$as_me:$LINENO: checking for XmCreateFontSelector in -lXm" >&5
+echo $ECHO_N "checking for XmCreateFontSelector in -lXm... $ECHO_C" >&6
+if test "${ac_cv_lib_Xm_XmCreateFontSelector+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXm $TEST_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XmCreateFontSelector ();
+int
+main ()
+{
+XmCreateFontSelector ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xm_XmCreateFontSelector=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xm_XmCreateFontSelector=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xm_XmCreateFontSelector" >&5
+echo "${ECHO_T}$ac_cv_lib_Xm_XmCreateFontSelector" >&6
+if test $ac_cv_lib_Xm_XmCreateFontSelector = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmCreateFontSelector 1
+_ACEOF
+
+fi
+
+   	  echo "$as_me:$LINENO: checking for XmCreateColorSelector in -lXm" >&5
+echo $ECHO_N "checking for XmCreateColorSelector in -lXm... $ECHO_C" >&6
+if test "${ac_cv_lib_Xm_XmCreateColorSelector+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXm $TEST_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XmCreateColorSelector ();
+int
+main ()
+{
+XmCreateColorSelector ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xm_XmCreateColorSelector=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xm_XmCreateColorSelector=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xm_XmCreateColorSelector" >&5
+echo "${ECHO_T}$ac_cv_lib_Xm_XmCreateColorSelector" >&6
+if test $ac_cv_lib_Xm_XmCreateColorSelector = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmCreateColorSelector 1
+_ACEOF
+
+fi
+
 	  echo "$as_me:$LINENO: checking whether sashes support relative panes" >&5
 echo $ECHO_N "checking whether sashes support relative panes... $ECHO_C" >&6
 	  cat >conftest.$ac_ext <<_ACEOF
