bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3837,7 +3837,8 @@ done
 
 
 
-for ac_header in libc.h sys/statvfs.h setjmp.h dlfcn.h sys/param.h byteswap.h stdint.h pthread.h
+
+for ac_header in libc.h sys/statvfs.h setjmp.h dlfcn.h sys/param.h byteswap.h stdint.h pthread.h sys/mount.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -8842,7 +8843,8 @@ done
 
 
 
-for ac_func in getcwd getwd strerror readlink setlocale access opendir sleep signal statvfs clock getline
+
+for ac_func in getcwd getwd strerror readlink setlocale access opendir sleep signal statvfs statfs clock getline
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -14760,7 +14762,7 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
   case "$host" in
     *-apple-*)
       GL_LIBS="-framework OpenGL"
-      # is this in place of or in additon to -lGL etc?
+      # is this in place of or in addition to -lGL etc?
       ;;
   esac
 else
@@ -19197,6 +19199,80 @@ echo "${ECHO_T}yes" >&6
     else
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+    fi
+  fi
+fi
+
+statfs_ok=0
+if test $statvfs_ok = 0 ; then
+  if test "$ac_cv_func_statfs" = yes ; then
+    if test "$ac_cv_header_sys_param_h" = yes ; then
+      if test "$ac_cv_header_sys_mount_h" = yes ; then
+        echo "$as_me:$LINENO: checking for statfs" >&5
+echo $ECHO_N "checking for statfs... $ECHO_C" >&6
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/param.h>
+                           #include <sys/mount.h>
+
+int
+main ()
+{
+struct statfs buf;
+                           int size = 0;
+  			   statfs("test.snd", &buf);
+                           if (buf.f_bsize = 1024)
+			     size = (int)(buf.f_bavail)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cat >>confdefs.h <<\_ACEOF
+#define USE_STATFS 1
+_ACEOF
+
+          statfs_ok=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+        if test $statfs_ok = 1; then
+          echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        else
+          echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        fi
+      fi
     fi
   fi
 fi
