bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12868,6 +12868,78 @@ _ACEOF
 fi
 
 	# gtk 2.5.6
+	echo "$as_me:$LINENO: checking for gtk_text_layout_get_iter_at_position in -lm" >&5
+echo $ECHO_N "checking for gtk_text_layout_get_iter_at_position in -lm... $ECHO_C" >&6
+if test "${ac_cv_lib_m_gtk_text_layout_get_iter_at_position+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lm $GTK_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gtk_text_layout_get_iter_at_position ();
+int
+main ()
+{
+gtk_text_layout_get_iter_at_position ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_m_gtk_text_layout_get_iter_at_position=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_m_gtk_text_layout_get_iter_at_position=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_m_gtk_text_layout_get_iter_at_position" >&5
+echo "${ECHO_T}$ac_cv_lib_m_gtk_text_layout_get_iter_at_position" >&6
+if test $ac_cv_lib_m_gtk_text_layout_get_iter_at_position = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTK_TEXT_LAYOUT_GET_ITER_AT_POSITION 1
+_ACEOF
+
+fi
+
+	# gtk 2.6.0
 
         if test "$with_x11" = yes ; then
 	  cat >>confdefs.h <<\_ACEOF
@@ -19392,6 +19464,7 @@ if test "$enable_snd_debug" = yes ; then
   CFLAGS="-I. $CFLAGS"
 else
   # this taken from swh-plugins-0.3.7/configure.in (with minor changes)
+  # -mcpu=v9 is reported to help on the Sun
   # MACHINE="-mcpu=${build_cpu} -march=${build_cpu}"
   # if test ${build_cpu} = "powerpc"; then MACHINE=""; fi
   # CFLAGS="-I. $CFLAGS ${MACHINE}"
