docs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13333,6 +13333,62 @@ _ACEOF
 
 fi
 
+    echo "$as_me:$LINENO: checking for scm_t_guard" >&5
+echo $ECHO_N "checking for scm_t_guard... $ECHO_C" >&6
+if test "${ac_cv_type_scm_t_guard+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <guile/gh.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+if ((scm_t_guard *) 0)
+  return 0;
+if (sizeof (scm_t_guard))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_scm_t_guard=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_type_scm_t_guard=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_scm_t_guard" >&5
+echo "${ECHO_T}$ac_cv_type_scm_t_guard" >&6
+if test $ac_cv_type_scm_t_guard = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_DYNAMIC_WIND 1
+_ACEOF
+
+fi
+
     LIBS="$OLD_LIBS"
     CFLAGS="$OLD_CFLAGS"
 
