more off_t

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9625,8 +9625,9 @@ done
 # -------- OpenGL --------
 GL_LIBS=""
 GL_FILES=""
+GL_FLAGS=""
 have_gl=no
-if test "$with_gl" = yes ; then
+if test "$with_gl" = yes || test "$with_just_gl" = yes ; then
   if test "${ac_cv_header_GL_gl_h+set}" = set; then
   echo "$as_me:$LINENO: checking for GL/gl.h" >&5
 echo $ECHO_N "checking for GL/gl.h... $ECHO_C" >&6
@@ -9729,13 +9730,113 @@ echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&6
 
 fi
 if test $ac_cv_header_GL_gl_h = yes; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_GL 1
+  have_gl=yes
+else
+  if test "${ac_cv_header__usr_X11R6_include_GL_gh_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for /usr/X11R6/include/GL/gh.h" >&5
+echo $ECHO_N "checking for /usr/X11R6/include/GL/gh.h... $ECHO_C" >&6
+if test "${ac_cv_header__usr_X11R6_include_GL_gh_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__usr_X11R6_include_GL_gh_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_X11R6_include_GL_gh_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking /usr/X11R6/include/GL/gh.h usability" >&5
+echo $ECHO_N "checking /usr/X11R6/include/GL/gh.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include </usr/X11R6/include/GL/gh.h>
 _ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
 
-	 have_gl=yes
-	 GL_FILES="gl.o"
-	 GL_LIBS="-lGLU -lGL"
+# Is the header present?
+echo "$as_me:$LINENO: checking /usr/X11R6/include/GL/gh.h presence" >&5
+echo $ECHO_N "checking /usr/X11R6/include/GL/gh.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include </usr/X11R6/include/GL/gh.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: /usr/X11R6/include/GL/gh.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: /usr/X11R6/include/GL/gh.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/X11R6/include/GL/gh.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /usr/X11R6/include/GL/gh.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: /usr/X11R6/include/GL/gh.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: /usr/X11R6/include/GL/gh.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/X11R6/include/GL/gh.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: /usr/X11R6/include/GL/gh.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/X11R6/include/GL/gh.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /usr/X11R6/include/GL/gh.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for /usr/X11R6/include/GL/gh.h" >&5
+echo $ECHO_N "checking for /usr/X11R6/include/GL/gh.h... $ECHO_C" >&6
+if test "${ac_cv_header__usr_X11R6_include_GL_gh_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__usr_X11R6_include_GL_gh_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__usr_X11R6_include_GL_gh_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_X11R6_include_GL_gh_h" >&6
+
+fi
+if test $ac_cv_header__usr_X11R6_include_GL_gh_h = yes; then
+  have_gl=yes
+		 GL_FLAGS="-I/usr/X11R6/include"
+
 else
   { echo "$as_me:$LINENO: WARNING: can't find GL headers" >&5
 echo "$as_me: WARNING: can't find GL headers" >&2;}
@@ -9743,132 +9844,27 @@ fi
 
 
 fi
-if test "$with_just_gl" = yes ; then
-  if test "${ac_cv_header_GL_gl_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for GL/gl.h" >&5
-echo $ECHO_N "checking for GL/gl.h... $ECHO_C" >&6
-if test "${ac_cv_header_GL_gl_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_GL_gl_h" >&5
-echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking GL/gl.h usability" >&5
-echo $ECHO_N "checking GL/gl.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-$ac_includes_default
-#include <GL/gl.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_header_compiler=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
 
-# Is the header present?
-echo "$as_me:$LINENO: checking GL/gl.h presence" >&5
-echo $ECHO_N "checking GL/gl.h presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <GL/gl.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  egrep -v '^ *\+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_c_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
 
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: GL/gl.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: GL/gl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&2;};;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: GL/gl.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: GL/gl.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/gl.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: GL/gl.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&2;};;
-esac
-echo "$as_me:$LINENO: checking for GL/gl.h" >&5
-echo $ECHO_N "checking for GL/gl.h... $ECHO_C" >&6
-if test "${ac_cv_header_GL_gl_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_GL_gl_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_GL_gl_h" >&5
-echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&6
-
-fi
-if test $ac_cv_header_GL_gl_h = yes; then
-  cat >>confdefs.h <<\_ACEOF
+  if test "$have_gl" = yes ; then
+    cat >>confdefs.h <<\_ACEOF
 #define HAVE_GL 1
 _ACEOF
 
-	 cat >>confdefs.h <<\_ACEOF
+    if test "$with_just_gl" = yes ; then
+      cat >>confdefs.h <<\_ACEOF
 #define JUST_GL 1
 _ACEOF
 
-	 have_gl=yes
-	 GL_FILES=""
-	 GL_LIBS="-lGLU -lGL"
-else
-  { echo "$as_me:$LINENO: WARNING: can't find GL headers" >&5
-echo "$as_me: WARNING: can't find GL headers" >&2;}
+    fi
+    GL_FILES="gl.o"
+    GL_LIBS="-lGLU -lGL"
+    if test "$with_gtk" = yes; then
+      GL_LIBS="$GL_LIBS -lgdkglext-x11-0.x -lgtkglext-x11-0.x"
+    fi
+  fi
 fi
 
-
-fi
-# if with_gl and with_gtk look got gtkglext
-# TODO: find the current version of libgtkglext somehow
-if test "$have_gl" = yes && test "$with_gtk" = yes; then
-  GL_LIBS="$GL_LIBS -lgdkglext-x11-0.x -lgtkglext-x11-0.x"
-fi
 
 
 
@@ -14914,6 +14910,7 @@ s,@GTKEXTRA_FLAGS@,$GTKEXTRA_FLAGS,;t t
 s,@FFTW_LIBS@,$FFTW_LIBS,;t t
 s,@GL_LIBS@,$GL_LIBS,;t t
 s,@GL_FILES@,$GL_FILES,;t t
+s,@GL_FLAGS@,$GL_FLAGS,;t t
 s,@X_CFLAGS@,$X_CFLAGS,;t t
 s,@X_PRE_LIBS@,$X_PRE_LIBS,;t t
 s,@X_LIBS@,$X_LIBS,;t t
