bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2938,7 +2938,7 @@ _ACEOF
 #   SNDLIB_CONFIG_path    where to look for sndlib-config
 #
 # SOMEDAY: --with-static-libraries --with-static-guile
-
+# TODO: update sndlib(jack) and libxm(gtkglext) configures
 
 #--------------------------------------------------------------------------------
 
@@ -14329,6 +14329,78 @@ _ACEOF
 fi
 
 	# gtk 2.3.2
+	echo "$as_me:$LINENO: checking for gtk_combo_box_popup in -lm" >&5
+echo $ECHO_N "checking for gtk_combo_box_popup in -lm... $ECHO_C" >&6
+if test "${ac_cv_lib_m_gtk_combo_box_popup+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lm $GTK_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gtk_combo_box_popup ();
+int
+main ()
+{
+gtk_combo_box_popup ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_m_gtk_combo_box_popup=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_m_gtk_combo_box_popup=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_m_gtk_combo_box_popup" >&5
+echo "${ECHO_T}$ac_cv_lib_m_gtk_combo_box_popup" >&6
+if test $ac_cv_lib_m_gtk_combo_box_popup = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTK_COMBO_BOX_POPUP 1
+_ACEOF
+
+fi
+
+	# gtk 2.3.4
 
         if test "$with_x11" = yes ; then
 	  cat >>confdefs.h <<\_ACEOF
