opts

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -868,7 +868,6 @@ Optional Packages:
   --with-static-gsl	  use libgsl.a to build Snd
   --with-static-xm	  include the xm module
   --with-guile		  use Guile
-  --with-run		  Guile optimizer
   --with-gl		  include OpenGL support
   --with-just-gl	  include OpenGL support, but omit the GL/Guile bindings
   --with-html		  include the XmHTML or mozilla browser library
@@ -876,6 +875,7 @@ Optional Packages:
   --with-static-motif	  use libXm.a to build Snd
   --with-modules	  use if sndlib uses modules
   --with-editres	  include editres in xm
+  --with-ladspa  	  include support for LADSPA plugins
   --with-float-samples	  use floats as the internal sample respresentation
   --with-sample-width=N   use N bits of samples
   --with-motif-prefix=PFX where Motif is installed
@@ -884,7 +884,6 @@ Optional Packages:
   --with-ruby-prefix=PFX  where Ruby is installed
   --with-ruby	  	  try to use Ruby as the extension language
   --with-snd-as-widget	  make Snd a loadable widget, not a standalone program
-  --with-ladspa	  	  include support for LADSPA plugins
   --with-x                use the X Window System
   --with-shared-sndlib	  try to load libsndlib.so
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
@@ -2800,7 +2799,6 @@ _ACEOF
 #   --with-static-xm      include xm module
 #   --with-temp-dir       directory to use for temp files
 #   --with-save-dir       directory to use for saved-state files
-#   --with-run            Guile optimizer (default=yes)
 #   --with-gl             include OpenGL support (default=no)
 #   --with-just-gl        include OpenGL support but omit the Guile bindings (gl.o) (default=no)
 #   --with-modules        accommodate sndlib that was built with modules
@@ -2863,12 +2861,6 @@ if test "${with_guile+set}" = set; then
 
 fi;
 
-# Check whether --with-run or --without-run was given.
-if test "${with_run+set}" = set; then
-  withval="$with_run"
-
-fi;
-
 # Check whether --with-gl or --without-gl was given.
 if test "${with_gl+set}" = set; then
   withval="$with_gl"
@@ -2908,6 +2900,12 @@ fi;
 # Check whether --with-editres or --without-editres was given.
 if test "${with_editres+set}" = set; then
   withval="$with_editres"
+
+fi;
+
+# Check whether --with-ladspa or --without-ladspa was given.
+if test "${with_ladspa+set}" = set; then
+  withval="$with_ladspa"
 
 fi;
 
@@ -3338,18 +3336,6 @@ _ACEOF
   fi
 fi;
 
-
-
-# Check whether --with-ladspa or --without-ladspa was given.
-if test "${with_ladspa+set}" = set; then
-  withval="$with_ladspa"
-  if test "$with_ladspa" = yes ; then
-	    cat >>confdefs.h <<\_ACEOF
-#define HAVE_LADSPA 1
-_ACEOF
-
-	fi
-fi;
 
 
 #--------------------------------------------------------------------------------
@@ -4038,8 +4024,7 @@ done
 
 
 
-
-for ac_header in libc.h sys/vfs.h sys/statfs.h sys/mount.h setjmp.h sched.h pwd.h ladspa.h locale.h sys/fpu.h dlfcn.h sys/param.h byteswap.h
+for ac_header in libc.h sys/vfs.h sys/statfs.h sys/mount.h setjmp.h sched.h pwd.h locale.h sys/fpu.h dlfcn.h sys/param.h byteswap.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -9782,6 +9767,146 @@ done
 
 # AC_CHECK_STRUCT_FOR([#include <sys/statfs.h>],statfs,f_bsize)
 
+if test "$with_ladspa" != no ; then
+  if test "${ac_cv_header_ladspa_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for ladspa.h" >&5
+echo $ECHO_N "checking for ladspa.h... $ECHO_C" >&6
+if test "${ac_cv_header_ladspa_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_ladspa_h" >&5
+echo "${ECHO_T}$ac_cv_header_ladspa_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking ladspa.h usability" >&5
+echo $ECHO_N "checking ladspa.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <ladspa.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking ladspa.h presence" >&5
+echo $ECHO_N "checking ladspa.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ladspa.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: ladspa.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: ladspa.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ladspa.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ladspa.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: ladspa.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: ladspa.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ladspa.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: ladspa.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ladspa.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ladspa.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for ladspa.h" >&5
+echo $ECHO_N "checking for ladspa.h... $ECHO_C" >&6
+if test "${ac_cv_header_ladspa_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_ladspa_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_ladspa_h" >&5
+echo "${ECHO_T}$ac_cv_header_ladspa_h" >&6
+
+fi
+if test $ac_cv_header_ladspa_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_LADSPA 1
+_ACEOF
+
+fi
+
+
+fi
+
 
 #--------------------------------------------------------------------------------
 # X/Motif/Gtk+
@@ -13984,17 +14109,11 @@ fi
     if test "`${GUILE_CONFIG_path}guile -c '(display (string<=? (version) "1.3.4"))'`" = "#t"; then
       echo found old out-of-date Guile library
     fi
-    if test "$with_run" != no; then
-      if test "`${GUILE_CONFIG_path}guile -c '(display (string>=? (version) "1.5"))'`" = "#t"; then
-        cat >>confdefs.h <<\_ACEOF
+    if test "`${GUILE_CONFIG_path}guile -c '(display (string>=? (version) "1.5"))'`" = "#t"; then
+      cat >>confdefs.h <<\_ACEOF
 #define WITH_RUN 1
 _ACEOF
 
-      else
-	if test "$with_run" = yes; then
-          echo --with-run switch is not compatible with Guile versions before 1.5
-	fi
-      fi
     fi
   fi
 else
