bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -852,10 +852,10 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-snd-debug      include internal Snd debugging functions
   --disable-largefile     omit support for large files
   --disable-rpath         do not hardcode runtime library paths
   --disable-nls           do not use Native Language Support
+  --enable-snd-debug      include internal Snd debugging functions
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3456,22 +3456,6 @@ _ACEOF
 
 	    MAKE_TARGET=widget
 	fi
-fi;
-
-# Check whether --enable-snd-debug or --disable-snd-debug was given.
-if test "${enable_snd_debug+set}" = set; then
-  enableval="$enable_snd_debug"
-  if test "$enable_snd_debug" = yes ; then
-    cat >>confdefs.h <<\_ACEOF
-#define DEBUGGING 1
-_ACEOF
-
-    cat >>confdefs.h <<\_ACEOF
-#define DEBUG_MEMORY 1
-_ACEOF
-
-    CFLAGS="$CFLAGS -g3 -Wall"
-  fi
 fi;
 
 
@@ -11127,6 +11111,65 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 fi
 
+echo "$as_me:$LINENO: checking for __func__" >&5
+echo $ECHO_N "checking for __func__... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+ char *s;
+      s = __func__
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE___FUNC__ 1
+_ACEOF
+
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+
 # -------- GSL --------
 GSL_LIBS=""
 GSL_CFLAGS=""
@@ -13491,10 +13534,6 @@ _ACEOF
           fi
 
 
-#   	  AC_CHECK_LIB(Xm, XmToolTipGetLabel, [AC_DEFINE(HAVE_XmToolTipGetLabel)], , $TEST_LIBS)
-#   	  AC_CHECK_LIB(Xm, XmCreateFontSelector, [AC_DEFINE(HAVE_XmCreateFontSelector)], , $TEST_LIBS)
-#   	  AC_CHECK_LIB(Xm, XmCreateColorSelector, [AC_DEFINE(HAVE_XmCreateColorSelector)], , $TEST_LIBS)
-# ac_check_lib is too easily fooled
           echo "$as_me:$LINENO: checking for XmCreateFontSelector" >&5
 echo $ECHO_N "checking for XmCreateFontSelector... $ECHO_C" >&6
           cat >conftest.$ac_ext <<_ACEOF
@@ -14520,6 +14559,12 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
       fi
       GL_LIBS="-lGLU -lGL"
+      case "$host" in
+        *-apple-*)
+	  GL_LIBS="-framework OpenGL"
+# is this in place of or in additon to -lGL etc?
+	  ;;
+      esac
       if test "$with_gtk" = yes; then
 # there's no gtkglext config program, as far as I can tell, so...
         OLD_CFLAGS="$CFLAGS"
@@ -20239,6 +20284,125 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 
+
+
+
+# Check whether --enable-snd-debug or --disable-snd-debug was given.
+if test "${enable_snd_debug+set}" = set; then
+  enableval="$enable_snd_debug"
+  if test "$enable_snd_debug" = yes ; then
+    cat >>confdefs.h <<\_ACEOF
+#define DEBUGGING 1
+_ACEOF
+
+    cat >>confdefs.h <<\_ACEOF
+#define DEBUG_MEMORY 1
+_ACEOF
+
+
+  ansi=
+  if test -z "$ansi"; then
+    msg="for C compiler warning flags"
+  else
+    msg="for C compiler warning and ANSI conformance flags"
+  fi
+  echo "$as_me:$LINENO: checking $msg" >&5
+echo $ECHO_N "checking $msg... $ECHO_C" >&6
+if test "${vl_cv_prog_cc_warnings+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    if test -n "$CC"; then
+      cat > conftest.c <<EOF
+int main(int argc, char **argv) { return 0; }
+EOF
+
+            if test "$GCC" = "yes"; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-g3 -Wall"
+        else
+          vl_cv_prog_cc_warnings="-g3 -Wall -ansi -pedantic"
+        fi
+
+
+            elif $CC -V 2>&1 | grep -i "WorkShop" > /dev/null 2>&1 &&
+           $CC -c -v -Xc conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-v"
+        else
+          vl_cv_prog_cc_warnings="-v -Xc"
+        fi
+
+            elif $CC -V 2>&1 | grep -i "Digital UNIX Compiler" > /dev/null 2>&1 &&
+           $CC -c -verbose -w0 -warnprotos -std1 conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-verbose -w0 -warnprotos"
+        else
+          vl_cv_prog_cc_warnings="-verbose -w0 -warnprotos -std1"
+        fi
+
+            elif $CC 2>&1 | grep -i "C for AIX Compiler" > /dev/null 2>&1 &&
+           $CC -c -qlanglvl=ansi -qinfo=all conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-qsrcmsg -qinfo=all:noppt:noppc:noobs:nocnd"
+        else
+          vl_cv_prog_cc_warnings="-qsrcmsg -qinfo=all:noppt:noppc:noobs:nocnd -qlanglvl=ansi"
+        fi
+
+            elif $CC -version 2>&1 | grep -i "MIPSpro Compilers" > /dev/null 2>&1 &&
+           $CC -c -fullwarn -ansi -ansiE conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-fullwarn"
+        else
+          vl_cv_prog_cc_warnings="-fullwarn -ansi -ansiE"
+        fi
+
+            elif what $CC 2>&1 | grep -i "HP C Compiler" > /dev/null 2>&1 &&
+           $CC -c -Aa +w1 conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="+w1"
+        else
+          vl_cv_prog_cc_warnings="+w1 -Aa"
+        fi
+
+            elif $CC -V 2>&1 | grep "/SX" > /dev/null 2>&1 &&
+           $CC -c -pvctl,fullmsg -Xc conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-pvctl,fullmsg"
+        else
+          vl_cv_prog_cc_warnings="-pvctl,fullmsg -Xc"
+        fi
+
+            elif $CC -V 2>&1 | grep -i "Cray" > /dev/null 2>&1 &&
+           $CC -c -h msglevel 2 conftest.c > /dev/null 2>&1 &&
+           test -f conftest.o; then
+        if test -z "$ansi"; then
+          vl_cv_prog_cc_warnings="-h msglevel 2"
+        else
+          vl_cv_prog_cc_warnings="-h msglevel 2 -h conform"
+        fi
+
+      fi
+      rm -f conftest.*
+    fi
+    if test -n "$vl_cv_prog_cc_warnings"; then
+      CFLAGS="$CFLAGS $vl_cv_prog_cc_warnings"
+    else
+      vl_cv_prog_cc_warnings="unknown"
+    fi
+
+fi
+echo "$as_me:$LINENO: result: $vl_cv_prog_cc_warnings" >&5
+echo "${ECHO_T}$vl_cv_prog_cc_warnings" >&6
+
+  fi
+fi;
 
 
 CFLAGS="-I. $CFLAGS"
