fftw

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9047,10 +9047,9 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-
-        echo "$as_me:$LINENO: result: yes" >&5
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-        cat >>confdefs.h <<\_ACEOF
+         	 cat >>confdefs.h <<\_ACEOF
 #define HAVE_ISNAN 1
 _ACEOF
 
@@ -9064,6 +9063,58 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 done
 
+
+SAVELIBS=$LIBS
+FFTW_LIBS=""
+LIBS="$LIBS -lrfftw -lfftw -lm"
+echo "$as_me:$LINENO: checking for rfftw" >&5
+echo $ECHO_N "checking for rfftw... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <rfftw.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+rfftw_one(NULL, NULL, NULL)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		 cat >>confdefs.h <<\_ACEOF
+#define HAVE_FFTW 1
+_ACEOF
+
+		 FFTW_LIBS="-lrfftw -lfftw"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+LIBS=$SAVELIBS
 
 echo "$as_me:$LINENO: checking return type of signal handlers" >&5
 echo $ECHO_N "checking return type of signal handlers... $ECHO_C" >&6
@@ -14859,6 +14910,7 @@ s,@GSL_CFLAGS@,$GSL_CFLAGS,;t t
 s,@GTKEXTRA_CONFIG@,$GTKEXTRA_CONFIG,;t t
 s,@GTKEXTRA_LIBS@,$GTKEXTRA_LIBS,;t t
 s,@GTKEXTRA_FLAGS@,$GTKEXTRA_FLAGS,;t t
+s,@FFTW_LIBS@,$FFTW_LIBS,;t t
 s,@GL_LIBS@,$GL_LIBS,;t t
 s,@GL_FILES@,$GL_FILES,;t t
 s,@X_CFLAGS@,$X_CFLAGS,;t t
