bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13645,6 +13645,124 @@ _ACEOF
           fi
 
 
+          echo "$as_me:$LINENO: checking for XmMultiList" >&5
+echo $ECHO_N "checking for XmMultiList... $ECHO_C" >&6
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Xm/XmAll.h>
+                 #include <Xm/MultiList.h>
+int
+main ()
+{
+ Widget w;
+                  w = XmCreateMultiList(NULL, "multilist", NULL, 0)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+ 	     cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmCreateMultiList 1
+_ACEOF
+
+	     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          echo "$as_me:$LINENO: checking for XmDataField" >&5
+echo $ECHO_N "checking for XmDataField... $ECHO_C" >&6
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Xm/XmAll.h>
+                 #include <Xm/DataF.h>
+int
+main ()
+{
+ Widget w;
+                  w = XmCreateDataField(NULL, "data-field", NULL, 0)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+ 	     cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmCreateDataField 1
+_ACEOF
+
+	     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
           echo "$as_me:$LINENO: checking for XmButtonBox" >&5
 echo $ECHO_N "checking for XmButtonBox... $ECHO_C" >&6
           cat >conftest.$ac_ext <<_ACEOF
@@ -15207,7 +15325,6 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
            GL_LIBS=$GL_LIBS" "`pkg-config gtkglext-1.0 --libs`
            GL_FLAGS=$GL_FLAGS" "`pkg-config gtkglext-1.0 --cflags`
         else
-# there's no gtkglext config program, as far as I can tell, so...
           OLD_CFLAGS="$CFLAGS"
 	  OLD_CPPFLAGS="$CPPFLAGS"
           CFLAGS="-I/usr/local/include/gtkglext-1.0 -I/usr/local/lib/gtkglext-1.0/include $GTK_CFLAGS $CFLAGS"
