bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -897,6 +897,7 @@ Optional Packages:
   --with-save-dir	  directory to use for saved-state files
   --with-doc-dir	  directory to search for documentation
   --with-snd-as-widget	  make Snd a loadable widget, not a standalone program
+  --with-snd-as-pd-external	  make Snd a loadable pd external, not a standalone program
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-x                use the X Window System
   --with-ruby-prefix=PFX  where Ruby is installed
@@ -2918,6 +2919,7 @@ _ACEOF
 #   --with-jack           use Jack
 #   --with-static-alsa    use ALSA statically loaded (for RPM generation)
 #   --with-snd-as-widget  make Snd a loadable widget, not a standalone program
+#   --with-snd-as-pd-external  make Snd a loadable pd external, not a standalone program
 #   --with-doubles        use doubles throughout (default is floats)
 #   --with-float-samples  represent samples internally as floats
 #   --enable-snd-debug    include Snd internal debugging stuff
@@ -3258,11 +3260,35 @@ fi;
 if test "${with_snd_as_widget+set}" = set; then
   withval="$with_snd_as_widget"
   if test "$with_snd_as_widget" = yes ; then
-	    cat >>confdefs.h <<\_ACEOF
+	   cat >>confdefs.h <<\_ACEOF
 #define SND_AS_WIDGET 1
 _ACEOF
 
-	    MAKE_TARGET=widget
+	   MAKE_TARGET=widget
+	fi
+fi;
+
+
+# Check whether --with-snd-as-pd-external or --without-snd-as-pd-external was given.
+if test "${with_snd_as_pd_external+set}" = set; then
+  withval="$with_snd_as_pd_external"
+  if test "$with_snd_as_pd_external" = yes ; then
+	   if test "$with_motif" = yes || test "$with_gtk" = yes ; then
+	      { { echo "$as_me:$LINENO: error: When making snd as a pd external" >&5
+echo "$as_me: error: When making snd as a pd external" >&2;}
+   { (exit motif or gtk can not be used.); exit motif or gtk can not be used.; }; }
+	   fi
+	   if test "$with_ruby" = yes ; then
+	      { { echo "$as_me:$LINENO: error: When making snd as a pd external" >&5
+echo "$as_me: error: When making snd as a pd external" >&2;}
+   { (exit ruby can not be used as extension language.); exit ruby can not be used as extension language.; }; }
+	   fi
+	   with_jack=yes
+	   cat >>confdefs.h <<\_ACEOF
+#define SND_AS_PD_EXTERNAL 1
+_ACEOF
+
+	   MAKE_TARGET=external
 	fi
 fi;
 
@@ -11777,7 +11803,7 @@ if test "$with_motif" = no && test "$with_gtk" = no ; then
   with_no_gui=yes
 fi
 
-if test "$no_x" = yes || test "$with_no_gui" = yes ; then
+if test "$no_x" = yes || test "$with_no_gui" = yes || test "$with_snd_as_pd_external"; then
 
   cat >>confdefs.h <<\_ACEOF
 #define USE_NO_GUI 1
@@ -15716,7 +15742,7 @@ fi
 GUILE_LIB_path=""
 XM_LIBS=""
 
-if test "$with_guile" = no ; then
+if test "$with_guile" = no && test "$with_snd_as_pd_external" = no; then
   cat >>confdefs.h <<\_ACEOF
 #define HAVE_GUILE 0
 _ACEOF
@@ -15811,6 +15837,11 @@ _ACEOF
         # the -pthread business confuses ld
         new_libs=`echo " $XM_LIBS " | sed -e 's/-pthread //'`
         LD_XM_LIBS="$new_libs"
+      fi
+      if test "$with_snd_as_pd_external" && test "`${GUILE_CONFIG_path}${GUILE_name} -c '(display (string>=? (version) "1.7.2"))'`" != "#t"; then
+	 { { echo "$as_me:$LINENO: error: Snd needs guile V1.7.2 or newer to work as a pd external" >&5
+echo "$as_me: error: Snd needs guile V1.7.2 or newer to work as a pd external" >&2;}
+   { (exit 1); exit 1; }; }
       fi
     fi
 
