xramp2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4006,7 +4006,8 @@ done
 
 
 
-for ac_header in libc.h sys/vfs.h sys/statfs.h sys/mount.h setjmp.h sched.h pwd.h ladspa.h locale.h sys/fpu.h dlfcn.h sys/param.h
+
+for ac_header in libc.h sys/vfs.h sys/statfs.h sys/mount.h setjmp.h sched.h pwd.h ladspa.h locale.h sys/fpu.h dlfcn.h sys/param.h byteswap.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -11885,6 +11886,68 @@ _ACEOF
 fi
 
 	# gtk 2.1
+	echo "$as_me:$LINENO: checking for gtk_tree_row_reference_get_type in -lgtk" >&5
+echo $ECHO_N "checking for gtk_tree_row_reference_get_type in -lgtk... $ECHO_C" >&6
+if test "${ac_cv_lib_gtk_gtk_tree_row_reference_get_type+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgtk $GTK_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gtk_tree_row_reference_get_type ();
+int
+main ()
+{
+gtk_tree_row_reference_get_type ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gtk_gtk_tree_row_reference_get_type=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gtk_gtk_tree_row_reference_get_type=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gtk_gtk_tree_row_reference_get_type" >&5
+echo "${ECHO_T}$ac_cv_lib_gtk_gtk_tree_row_reference_get_type" >&6
+if test $ac_cv_lib_gtk_gtk_tree_row_reference_get_type = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTK_TREE_ROW_REFERENCE_GET_TYPE 1
+_ACEOF
+
+fi
+
+	# gtk 2.2
 
 	if test "$with_html" = yes ; then
 	  # Extract the first word of "mozilla-config", so it can be a program name with args.
