with-relative-panes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11344,6 +11344,55 @@ fi
 _ACEOF
 
           fi
+	  echo "$as_me:$LINENO: checking sash support for relative panes" >&5
+echo $ECHO_N "checking sash support for relative panes... $ECHO_C" >&6
+	  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <Xm/SashP.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ Widget w; SashCallData call_data;
+                           if ((XtIsSubclass(w, xmSashWidgetClass)) && (strcmp(call_data->params[0], "Start") == 0)) return;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+			  cat >>confdefs.h <<\_ACEOF
+#define WITH_RELATIVE_PANES 1
+_ACEOF
+
+			  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
 
 else
 
