ops

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12394,8 +12394,152 @@ rm -f conftest.$ac_objext conftest.$ac_ext
       fi
       GL_LIBS="-lGLU -lGL"
       if test "$with_gtk" = yes; then
-        GL_LIBS="$GL_LIBS -lgdkglext-x11-0.x -lgtkglext-x11-0.x"
-        GL_FLAGS="$GL_FLAGS -I/usr/local/include/gtkglext-0.x"
+# there's no gtkglext config program, as far as I can tell, so...
+        OLD_CFLAGS="$CFLAGS"
+        CFLAGS="-I/usr/local/include/gtkglext-1.0 -I/usr/local/lib/gtkglext-1.0/include $GTK_CFLAGS $CFLAGS"
+	if test "${ac_cv_header_gtk_gtkgl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for gtk/gtkgl.h" >&5
+echo $ECHO_N "checking for gtk/gtkgl.h... $ECHO_C" >&6
+if test "${ac_cv_header_gtk_gtkgl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gtk_gtkgl_h" >&5
+echo "${ECHO_T}$ac_cv_header_gtk_gtkgl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking gtk/gtkgl.h usability" >&5
+echo $ECHO_N "checking gtk/gtkgl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <gtk/gtkgl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking gtk/gtkgl.h presence" >&5
+echo $ECHO_N "checking gtk/gtkgl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gtk/gtkgl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: gtk/gtkgl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gtk/gtkgl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gtk/gtkgl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gtk/gtkgl.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: gtk/gtkgl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gtk/gtkgl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gtk/gtkgl.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gtk/gtkgl.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gtk/gtkgl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gtk/gtkgl.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for gtk/gtkgl.h" >&5
+echo $ECHO_N "checking for gtk/gtkgl.h... $ECHO_C" >&6
+if test "${ac_cv_header_gtk_gtkgl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_gtk_gtkgl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gtk_gtkgl_h" >&5
+echo "${ECHO_T}$ac_cv_header_gtk_gtkgl_h" >&6
+
+fi
+if test $ac_cv_header_gtk_gtkgl_h = yes; then
+
+            GL_LIBS="$GL_LIBS -lgdkglext-x11-1.0 -lgtkglext-x11-1.0"
+            GL_FLAGS="$GL_FLAGS -I/usr/local/include/gtkglext-1.0 -I/usr/local/lib/gtkglext-1.0/include"
+
+else
+
+            GL_LIBS="$GL_LIBS -lgdkglext-x11-0.x -lgtkglext-x11-0.x"
+            GL_FLAGS="$GL_FLAGS -I/usr/local/include/gtkglext-0.x"
+
+fi
+
+
+	CFLAGS="$OLD_CFLAGS"
         echo "$as_me:$LINENO: checking for gdk_window_get_gl_config in -lm" >&5
 echo $ECHO_N "checking for gdk_window_get_gl_config in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_gdk_window_get_gl_config+set}" = set; then
