bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15054,6 +15054,76 @@ _ACEOF
 fi
 
 
+	# for 2.13.0
+	{ echo "$as_me:$LINENO: checking for gtk_test_widget_click in -lm" >&5
+echo $ECHO_N "checking for gtk_test_widget_click in -lm... $ECHO_C" >&6; }
+if test "${ac_cv_lib_m_gtk_test_widget_click+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lm $GTK_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gtk_test_widget_click ();
+int
+main ()
+{
+return gtk_test_widget_click ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_m_gtk_test_widget_click=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_m_gtk_test_widget_click=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_m_gtk_test_widget_click" >&5
+echo "${ECHO_T}$ac_cv_lib_m_gtk_test_widget_click" >&6; }
+if test $ac_cv_lib_m_gtk_test_widget_click = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTK_TEST_WIDGET_CLICK 1
+_ACEOF
+
+fi
+
+
 	# for gdk|pango_cairo
 	{ echo "$as_me:$LINENO: checking for gdk_cairo_create in -lm" >&5
 echo $ECHO_N "checking for gdk_cairo_create in -lm... $ECHO_C" >&6; }
@@ -24870,9 +24940,9 @@ fi
 { echo "$as_me:$LINENO: result:
   Options selected
   -------------------------
-  Snd version .......... : $VERSION
-  CFLAGS ............... : $CFLAGS
-  LDFLAGS .............. :$LDFLAGS
+  Snd version ...........: $VERSION
+  CFLAGS ................: $CFLAGS
+  LDFLAGS ...............:$LDFLAGS
   prefix.................: ${prefix}
   extension language.....: $LOCAL_LANGUAGE
   audio system...........: $AUDIO_SYSTEM
@@ -24884,9 +24954,9 @@ fi
 echo "${ECHO_T}
   Options selected
   -------------------------
-  Snd version .......... : $VERSION
-  CFLAGS ............... : $CFLAGS
-  LDFLAGS .............. :$LDFLAGS
+  Snd version ...........: $VERSION
+  CFLAGS ................: $CFLAGS
+  LDFLAGS ...............:$LDFLAGS
   prefix.................: ${prefix}
   extension language.....: $LOCAL_LANGUAGE
   audio system...........: $AUDIO_SYSTEM
