bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16951,6 +16951,7 @@ _ACEOF
         LIBS="-lm"
 
         audio_system=OSS
+
 	if test "$with_alsa" = yes || test "$with_static_alsa" = yes ; then
           echo "$as_me:$LINENO: checking for main in -lasound" >&5
 echo $ECHO_N "checking for main in -lasound... $ECHO_C" >&6
@@ -17305,8 +17306,9 @@ else
 echo "$as_me: WARNING: can't find the ALSA library" >&2;}
 fi
 
-	else
-	  if test "$with_jack" = yes ; then
+	fi
+
+	if test "$with_jack" = yes ; then
             echo "$as_me:$LINENO: checking for main in -ljack" >&5
 echo $ECHO_N "checking for main in -ljack... $ECHO_C" >&6
 if test "${ac_cv_lib_jack_main+set}" = set; then
@@ -17505,7 +17507,7 @@ echo "${ECHO_T}$ac_cv_header_jack_jack_h" >&6
 
 fi
 if test $ac_cv_header_jack_jack_h = yes; then
-  audio_system=JACK
+  :
 else
   with_jack=no
                    { echo "$as_me:$LINENO: WARNING: can't find the JACK header files" >&5
@@ -17519,7 +17521,223 @@ else
 echo "$as_me: WARNING: can't find the JACK library" >&2;}
 fi
 
-          fi
+            echo "$as_me:$LINENO: checking for main in -lsamplerate" >&5
+echo $ECHO_N "checking for main in -lsamplerate... $ECHO_C" >&6
+if test "${ac_cv_lib_samplerate_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsamplerate  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_samplerate_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_samplerate_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_samplerate_main" >&5
+echo "${ECHO_T}$ac_cv_lib_samplerate_main" >&6
+if test $ac_cv_lib_samplerate_main = yes; then
+
+	      if test "${ac_cv_header_samplerate_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for samplerate.h" >&5
+echo $ECHO_N "checking for samplerate.h... $ECHO_C" >&6
+if test "${ac_cv_header_samplerate_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_samplerate_h" >&5
+echo "${ECHO_T}$ac_cv_header_samplerate_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking samplerate.h usability" >&5
+echo $ECHO_N "checking samplerate.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <samplerate.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking samplerate.h presence" >&5
+echo $ECHO_N "checking samplerate.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <samplerate.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: samplerate.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: samplerate.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: samplerate.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: samplerate.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: samplerate.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: samplerate.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: samplerate.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: samplerate.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: samplerate.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------- ##
+## Report this to bil@ccrma.stanford.edu ##
+## ------------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for samplerate.h" >&5
+echo $ECHO_N "checking for samplerate.h... $ECHO_C" >&6
+if test "${ac_cv_header_samplerate_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_samplerate_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_samplerate_h" >&5
+echo "${ECHO_T}$ac_cv_header_samplerate_h" >&6
+
+fi
+if test $ac_cv_header_samplerate_h = yes; then
+  :
+else
+  with_jack=no
+                   { echo "$as_me:$LINENO: WARNING: can't find the samplerate header files. JACK will not be used." >&5
+echo "$as_me: WARNING: can't find the samplerate header files. JACK will not be used." >&2;}
+fi
+
+
+else
+  with_jack=no
+	       { echo "$as_me:$LINENO: WARNING: can't find the samplerate library. JACK will not be used." >&5
+echo "$as_me: WARNING: can't find the samplerate library. JACK will not be used." >&2;}
+fi
+
+            if test $with_jack = yes ; then
+	       if test $audio_system = OSS ; then
+                 audio_system=JACK
+               fi
+            fi
         fi
 
 	case $audio_system in
@@ -17649,9 +17867,9 @@ _ACEOF
 
 		    if test "$with_jack" = yes ; then
 		      if test "$with_static_alsa" = yes ; then
-			 AUDIO_LIB="/usr/lib/libasound.a -ljack"
+			 AUDIO_LIB="/usr/lib/libasound.a -ljack -lsamplerate"
 		      else
-			 AUDIO_LIB="-lasound -ljack"
+			 AUDIO_LIB="-lasound -ljack -lsamplerate"
 	              fi
 		      cat >>confdefs.h <<\_ACEOF
 #define HAVE_JACK 1
@@ -17671,7 +17889,11 @@ _ACEOF
 #define HAVE_JACK 1
 _ACEOF
 
-		AUDIO_LIB="-ljack"
+		cat >>confdefs.h <<\_ACEOF
+#define HAVE_OSS 1
+_ACEOF
+
+		AUDIO_LIB="-ljack -lsamplerate"
 		;;
 	    OSS)
 		cat >>confdefs.h <<\_ACEOF
@@ -17820,14 +18042,6 @@ _ACEOF
 _ACEOF
 
 	audio_system=Sun
-        ;;
-    *-*-sco*)
-        cat >>confdefs.h <<\_ACEOF
-#define SCO5 1
-_ACEOF
-
-	audio_system=OSS
-	LDSO_FLAGS="-belf -dy -Bdynamic -G"
         ;;
     *-*-cygwin*)
 	cat >>confdefs.h <<\_ACEOF
