bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11530,6 +11530,11 @@ if test $ac_cv_header_ladspa_h = yes; then
 #define HAVE_LADSPA 1
 _ACEOF
 
+else
+  if test "$with_ladspa" = yes ; then
+		   { echo "$as_me:$LINENO: WARNING: can't find ladspa.h!" >&5
+echo "$as_me: WARNING: can't find ladspa.h!" >&2;}
+		  fi
 fi
 
 
@@ -13776,7 +13781,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
- Widget w;
+ Widget w; int i; i = XmIconTop;
                   w = XmCreateButtonBox(NULL, "button-box", NULL, 0)
 
   ;
@@ -13808,6 +13813,65 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
 
  	     cat >>confdefs.h <<\_ACEOF
 #define HAVE_XmCreateButtonBox 1
+_ACEOF
+
+	     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          echo "$as_me:$LINENO: checking for XmTabStack" >&5
+echo $ECHO_N "checking for XmTabStack... $ECHO_C" >&6
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Xm/XmAll.h>
+                 #include <Xm/TabStack.h>
+int
+main ()
+{
+ Widget w;
+                  w = XmCreateTabStack(NULL, "tab-stack", NULL, 0)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+ 	     cat >>confdefs.h <<\_ACEOF
+#define HAVE_XmCreateTabStack 1
 _ACEOF
 
 	     echo "$as_me:$LINENO: result: yes" >&5
