opengl

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -852,6 +852,7 @@ Optional Packages:
   --with-guile		  use Guile
   --with-run		  Guile optimizer
   --with-gl		  include OpenGL support
+  --with-just-gl	  include OpenGL support, but omit the GL/Guile bindings
   --with-html		  include the XmHTML or mozilla browser library
   --with-big-colormap	  assume at least 512 colors are available (default=yes)
   --with-motif		  use libXm to build Snd
@@ -2531,6 +2532,7 @@ MAKE_TARGET="snd"
 #   --with-save-dir       directory to use for saved-state files
 #   --with-run            Guile optimizer (default=yes)
 #   --with-gl             include OpenGL support (default=no)
+#   --with-just-gl        include OpenGL support but omit the Guile bindings (gl.o) (default=no)
 #--------------------------------------------------------------------------------
 
 
@@ -2597,6 +2599,12 @@ fi;
 # Check whether --with-gl or --without-gl was given.
 if test "${with_gl+set}" = set; then
   withval="$with_gl"
+
+fi;
+
+# Check whether --with-just-gl or --without-just-gl was given.
+if test "${with_just_gl+set}" = set; then
+  withval="$with_just_gl"
 
 fi;
 
@@ -2844,6 +2852,76 @@ _ACEOF
 fi
 
 
+
+
+              OLD_LIBS="$LIBS"
+    	      LIBS="$GUILE_LIBS"
+              OLD_CFLAGS="$CFLAGS"
+              CFLAGS="$GUILE_CFLAGS -lm"
+              echo "$as_me:$LINENO: checking for rb_big2ll in -lruby" >&5
+echo $ECHO_N "checking for rb_big2ll in -lruby... $ECHO_C" >&6
+if test "${ac_cv_lib_ruby_rb_big2ll+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lruby  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char rb_big2ll ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+rb_big2ll ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ruby_rb_big2ll=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_ruby_rb_big2ll=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ruby_rb_big2ll" >&5
+echo "${ECHO_T}$ac_cv_lib_ruby_rb_big2ll" >&6
+if test $ac_cv_lib_ruby_rb_big2ll = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_RB_BIG2LL 1
+_ACEOF
+
+fi
+
+              LIBS="$OLD_LIBS"
+              CFLAGS="$OLD_CFLAGS"
 
             else
               { echo "$as_me:$LINENO: WARNING: can't find Ruby!" >&5
@@ -9624,6 +9702,127 @@ if test $ac_cv_header_GL_gl_h = yes; then
 _ACEOF
 
 	 GL_FILES="gl.o"
+	 GL_LIBS="-lGLU -lGL"
+else
+  { echo "$as_me:$LINENO: WARNING: can't find GL headers" >&5
+echo "$as_me: WARNING: can't find GL headers" >&2;}
+fi
+
+
+fi
+# TODO: if with-gl but not GL_COLOR_TABLE_SCALE, try just_gl case
+if test "$with_just_gl" = yes ; then
+  if test "${ac_cv_header_GL_gl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for GL/gl.h" >&5
+echo $ECHO_N "checking for GL/gl.h... $ECHO_C" >&6
+if test "${ac_cv_header_GL_gl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_GL_gl_h" >&5
+echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking GL/gl.h usability" >&5
+echo $ECHO_N "checking GL/gl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <GL/gl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking GL/gl.h presence" >&5
+echo $ECHO_N "checking GL/gl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <GL/gl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: GL/gl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: GL/gl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: GL/gl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: GL/gl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/gl.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: GL/gl.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: GL/gl.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for GL/gl.h" >&5
+echo $ECHO_N "checking for GL/gl.h... $ECHO_C" >&6
+if test "${ac_cv_header_GL_gl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_GL_gl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_GL_gl_h" >&5
+echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&6
+
+fi
+if test $ac_cv_header_GL_gl_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GL 1
+_ACEOF
+
+	 cat >>confdefs.h <<\_ACEOF
+#define JUST_GL 1
+_ACEOF
+
+	 GL_FILES=""
 	 GL_LIBS="-lGLU -lGL"
 else
   { echo "$as_me:$LINENO: WARNING: can't find GL headers" >&5
