bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4121,7 +4121,8 @@ done
 
 
 
-for ac_header in libc.h sys/vfs.h sys/statfs.h sys/mount.h setjmp.h sched.h pwd.h locale.h sys/fpu.h dlfcn.h sys/param.h byteswap.h
+
+for ac_header in libc.h sys/vfs.h sys/statfs.h sys/statvfs.h sys/mount.h setjmp.h sched.h pwd.h locale.h sys/fpu.h dlfcn.h sys/param.h byteswap.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -9657,7 +9658,8 @@ done
 
 
 
-for ac_func in getcwd strerror readlink setlocale access opendir sleep signal strdup statfs clock vsnprintf snprintf memmove
+
+for ac_func in getcwd strerror readlink setlocale access opendir sleep signal strdup statfs statvfs clock vsnprintf snprintf memmove
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -14022,6 +14024,67 @@ echo "${ECHO_T}$ac_cv_lib_guile_scm_mem2string" >&6
 if test $ac_cv_lib_guile_scm_mem2string = yes; then
   cat >>confdefs.h <<\_ACEOF
 #define HAVE_SCM_MEM2STRING 1
+_ACEOF
+
+fi
+
+    echo "$as_me:$LINENO: checking for scm_continuation_p in -lguile" >&5
+echo $ECHO_N "checking for scm_continuation_p in -lguile... $ECHO_C" >&6
+if test "${ac_cv_lib_guile_scm_continuation_p+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lguile  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char scm_continuation_p ();
+int
+main ()
+{
+scm_continuation_p ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_guile_scm_continuation_p=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_guile_scm_continuation_p=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_guile_scm_continuation_p" >&5
+echo "${ECHO_T}$ac_cv_lib_guile_scm_continuation_p" >&6
+if test $ac_cv_lib_guile_scm_continuation_p = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_SCM_CONTINUATION_P 1
 _ACEOF
 
 fi
