bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9300,10 +9300,55 @@ done
 
 SAVELIBS=$LIBS
 FFTW_LIBS=""
-LIBS="$LIBS -lrfftw -lfftw -lm"
-echo "$as_me:$LINENO: checking for rfftw" >&5
-echo $ECHO_N "checking for rfftw... $ECHO_C" >&6
+LIBS="$LIBS -lfftw3 -lm"
+echo "$as_me:$LINENO: checking for fftw-3" >&5
+echo $ECHO_N "checking for fftw-3... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <fftw3.h>
+int
+main ()
+{
+fftw_plan plan; fftw_execute(plan)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		 cat >>confdefs.h <<\_ACEOF
+#define HAVE_FFTW3 1
+_ACEOF
+
+		 FFTW_LIBS="-lfftw3"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                 LIBS=$SAVELIBS
+                 LIBS="$LIBS -lrfftw -lfftw -lm"
+                 echo "$as_me:$LINENO: checking for fftw-2" >&5
+echo $ECHO_N "checking for fftw-2... $ECHO_C" >&6
+                 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -9333,17 +9378,20 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-		 cat >>confdefs.h <<\_ACEOF
+		   		 cat >>confdefs.h <<\_ACEOF
 #define HAVE_FFTW 1
 _ACEOF
 
-		 FFTW_LIBS="-lrfftw -lfftw"
+		   		 FFTW_LIBS="-lrfftw -lfftw"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
