ptree edop

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9909,6 +9909,68 @@ _ACEOF
     GL_LIBS="-lGLU -lGL"
     if test "$with_gtk" = yes; then
       GL_LIBS="$GL_LIBS -lgdkglext-x11-0.x -lgtkglext-x11-0.x"
+      echo "$as_me:$LINENO: checking for gdk_window_get_gl_config in -lm" >&5
+echo $ECHO_N "checking for gdk_window_get_gl_config in -lm... $ECHO_C" >&6
+if test "${ac_cv_lib_m_gdk_window_get_gl_config+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lm $GL_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gdk_window_get_gl_config ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+gdk_window_get_gl_config ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_m_gdk_window_get_gl_config=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_m_gdk_window_get_gl_config=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_m_gdk_window_get_gl_config" >&5
+echo "${ECHO_T}$ac_cv_lib_m_gdk_window_get_gl_config" >&6
+if test $ac_cv_lib_m_gdk_window_get_gl_config = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GTK_GL_EXT_0_1 1
+_ACEOF
+
+fi
+
     fi
   fi
 fi
