bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18013,94 +18013,7 @@ if test "$with_alsa" = yes && test "$with_oss" = yes ; then
 echo "$as_me: WARNING: You asked for both ALSA and OSS -- OSS will be used" >&2;}
 fi
 
-case "$host" in
-    *-*-linux*)
-	cat >>confdefs.h <<\_ACEOF
-#define MUS_LINUX 1
-_ACEOF
-
-        LDSO_FLAGS="-shared"
-        LIBS="$LIBS -lm"
-	if test "$GCC" = yes ; then
-	  SO_FLAGS="-fPIC $SO_FLAGS"
-        fi
-
-        AUDIO_SYSTEM=OSS
-
-	if test "$with_alsa" = yes || test "$with_static_alsa" = yes ; then
-          if test "$ac_cv_header_alsa_asoundlib_h" = yes ; then
-            echo "$as_me:$LINENO: checking for main in -lasound" >&5
-echo $ECHO_N "checking for main in -lasound... $ECHO_C" >&6
-if test "${ac_cv_lib_asound_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lasound  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_asound_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_asound_main=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_asound_main" >&5
-echo "${ECHO_T}$ac_cv_lib_asound_main" >&6
-if test $ac_cv_lib_asound_main = yes; then
-  AUDIO_SYSTEM=ALSA
-else
-  { echo "$as_me:$LINENO: WARNING: can't find the ALSA library" >&5
-echo "$as_me: WARNING: can't find the ALSA library" >&2;}
-fi
-
-          else
-            { echo "$as_me:$LINENO: WARNING: can't find the ALSA header files" >&5
-echo "$as_me: WARNING: can't find the ALSA header files" >&2;}
-          fi
-	fi
-
-	if test "$with_jack" = yes ; then
+if test "$with_jack" = yes ; then
             echo "$as_me:$LINENO: checking for main in -ljack" >&5
 echo $ECHO_N "checking for main in -ljack... $ECHO_C" >&6
 if test "${ac_cv_lib_jack_main+set}" = set; then
@@ -18526,9 +18439,11 @@ echo "$as_me: WARNING: can't find the samplerate library. JACK will not be used.
 fi
 
             if test $with_jack = yes ; then
-	       if test "$with_alsa" != yes ; then
-                 AUDIO_SYSTEM=JACK
-               fi
+               AUDIO_SYSTEM=JACK
+	       cat >>confdefs.h <<\_ACEOF
+#define MUS_JACK 1
+_ACEOF
+
 	       if test x$PKG_CONFIG != xno ; then
                    jack_version="`$PKG_CONFIG jack --modversion`"
                    cat >>confdefs.h <<_ACEOF
@@ -18539,7 +18454,101 @@ _ACEOF
           	   JACK_FLAGS="`$PKG_CONFIG jack --cflags`"
                fi
             fi
+fi
+
+
+case "$host" in
+    *-*-linux*)
+	cat >>confdefs.h <<\_ACEOF
+#define MUS_LINUX 1
+_ACEOF
+
+        LDSO_FLAGS="-shared"
+        LIBS="$LIBS -lm"
+	if test "$GCC" = yes ; then
+	  SO_FLAGS="-fPIC $SO_FLAGS"
         fi
+
+        AUDIO_SYSTEM=OSS
+
+	if test "$with_alsa" = yes || test "$with_static_alsa" = yes ; then
+          if test "$ac_cv_header_alsa_asoundlib_h" = yes ; then
+            echo "$as_me:$LINENO: checking for main in -lasound" >&5
+echo $ECHO_N "checking for main in -lasound... $ECHO_C" >&6
+if test "${ac_cv_lib_asound_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lasound  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_asound_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_asound_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_asound_main" >&5
+echo "${ECHO_T}$ac_cv_lib_asound_main" >&6
+if test $ac_cv_lib_asound_main = yes; then
+  AUDIO_SYSTEM=ALSA
+else
+  { echo "$as_me:$LINENO: WARNING: can't find the ALSA library" >&5
+echo "$as_me: WARNING: can't find the ALSA library" >&2;}
+fi
+
+          else
+            { echo "$as_me:$LINENO: WARNING: can't find the ALSA header files" >&5
+echo "$as_me: WARNING: can't find the ALSA header files" >&2;}
+          fi
+	fi
+
+	if test "$with_jack" = yes ; then
+	       if test "$with_alsa" != yes ; then
+                 AUDIO_SYSTEM=JACK
+               fi
+	fi
 
 	case $AUDIO_SYSTEM in
 	    ALSA)
@@ -18865,37 +18874,40 @@ _ACEOF
         fi
         ;;
     *-*-cygwin*)
-	cat >>confdefs.h <<\_ACEOF
+	if test "$with_jack" != yes ; then
+	    cat >>confdefs.h <<\_ACEOF
 #define MUS_WINDOZE 1
 _ACEOF
 
-	AUDIO_SYSTEM=Windoze
+	    AUDIO_SYSTEM=Windoze
+	fi
 	;;
     *-apple-*)
-	cat >>confdefs.h <<\_ACEOF
+	if test "$with_jack" != yes ; then
+	    cat >>confdefs.h <<\_ACEOF
 #define MUS_MAC_OSX 1
 _ACEOF
 
-	AUDIO_SYSTEM=MacOSX
-	AUDIO_LIB="-framework CoreAudio -framework CoreFoundation -framework CoreMIDI"
+	    AUDIO_SYSTEM=MacOSX
+	    AUDIO_LIB="-framework CoreAudio -framework CoreFoundation -framework CoreMIDI"
 
-	echo "$as_me:$LINENO: checking for kAudioDevicePropertyDeviceManufacturer" >&5
+	    echo "$as_me:$LINENO: checking for kAudioDevicePropertyDeviceManufacturer" >&5
 echo $ECHO_N "checking for kAudioDevicePropertyDeviceManufacturer... $ECHO_C" >&6
-	cat >conftest.$ac_ext <<_ACEOF
+	    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <CoreServices/CoreServices.h>
-                            #include <CoreAudio/CoreAudio.h>
+                                #include <CoreAudio/CoreAudio.h>
 int
 main ()
 {
 AudioDeviceID deviceID;
-			    UInt32 trans_size = 0, trans;
-      			    trans_size = sizeof(UInt32);
-     			    AudioDeviceGetProperty(deviceID, 0, true, kAudioDevicePropertyTransportType, &trans_size, &trans)
+			        UInt32 trans_size = 0, trans;
+      			        trans_size = sizeof(UInt32);
+     			        AudioDeviceGetProperty(deviceID, 0, true, kAudioDevicePropertyTransportType, &trans_size, &trans)
 
   ;
   return 0;
@@ -18927,7 +18939,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 #define HAVE_KAUDIODEVICEPROPERTYTRANSPORTTYPE 1
 _ACEOF
 
-	   echo "$as_me:$LINENO: result: yes" >&5
+	       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
   echo "$as_me: failed program was:" >&5
@@ -18937,16 +18949,16 @@ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-	echo "$as_me:$LINENO: checking for kLinearPCMFormatFlagIsNonInterleaved" >&5
+	    echo "$as_me:$LINENO: checking for kLinearPCMFormatFlagIsNonInterleaved" >&5
 echo $ECHO_N "checking for kLinearPCMFormatFlagIsNonInterleaved... $ECHO_C" >&6
-	cat >conftest.$ac_ext <<_ACEOF
+	    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <CoreServices/CoreServices.h>
-                            #include <CoreAudio/CoreAudio.h>
+                                #include <CoreAudio/CoreAudio.h>
 int
 main ()
 {
@@ -18981,7 +18993,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 #define HAVE_KLINEARPCMFORMATFLAGISNONINTERLEAVED 1
 _ACEOF
 
-	   echo "$as_me:$LINENO: result: yes" >&5
+	       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
   echo "$as_me: failed program was:" >&5
@@ -18991,6 +19003,7 @@ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	fi
 	;;
 esac
 echo "$as_me:$LINENO: checking for audio system" >&5
